version: '3.5'

services:
  db:
    image: postgres:14.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
